dist: bionic
language: python
python:
  - "3.7"
install:
  - pip install --requirement requirements.txt
  - pip install --editable .
script:
  - pytest --cov=nerd --cov-report=term --verbose
after_success:
  - codecov
